version: '3'
services: 
    cassandraconnectivity:
        build: 
            context: .
        image: 'cassandraconnectivity'
        ports: 
            - "4070:4070"
        restart: always
    apachecassandra:
        image: 'cassandra'
        ports:
            - "9042:9042"
            - "9160:9160"
            - "7199:7199"
        container_name: 'apachecassandra'